"use client";

import React, { useState } from 'react';
import { X, Printer, Copy, Check, FileText } from 'lucide-react';
import { Language, translations } from '../lib/translations';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  filename: string;
  analysis: any;
  actionPlan: any;
  language: Language;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  filename,
  analysis,
  actionPlan,
  language,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !analysis) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleCopyText = () => {
    const textReport = `
==================================================
NYAYAAI LEGAL RISK AUDIT REPORT
Document: ${filename || 'Uploaded Contract'}
==================================================

PLAIN LANGUAGE SUMMARY:
${analysis.summary || 'N/A'}

RISK SCORE: ${analysis.risk_score || 0}/100

LEGAL RISKS:
${(analysis.risk_breakdown || [])
  .map(
    (r: any, i: number) =>
      `${i + 1}. [${r.severity.toUpperCase()}] ${r.issue}\n   Explanation: ${r.explanation}\n   Impact: ${r.impact}`
  )
  .join('\n\n')}

${
  actionPlan
    ? `
ACTION PLAN STEPS:
${(actionPlan.action_plan || [])
  .map((a: any, i: number) => `${i + 1}. ${a.action} (${a.priority} Priority - Deadline: ${a.deadline})`)
  .join('\n')}

EVIDENCE CHECKLIST:
${(actionPlan.evidence_checklist || []).map((e: string) => `- [ ] ${e}`).join('\n')}

QUESTIONS FOR LAWYER:
${(actionPlan.lawyer_questions || []).map((q: string, i: number) => `${i + 1}. ${q}`).join('\n')}
`
    : ''
}
--------------------------------------------------
Generated by NyayaAI - Grounded Legal Action Navigator
`.trim();

    navigator.clipboard.writeText(textReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white w-full max-w-2xl rounded-2xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-900 text-white">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-400" />
            <h3 className="font-bold text-base">Export Legal Audit Report</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 hover:bg-slate-800 rounded-lg transition-colors text-slate-300"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body Preview */}
        <div className="p-6 overflow-y-auto space-y-4 text-xs text-slate-700 bg-slate-50 border-b border-slate-100 flex-1">
          <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm space-y-4 font-sans">
            <div className="flex justify-between items-center border-b border-slate-100 pb-3">
              <div>
                <span className="font-bold text-slate-900 text-sm block">NyayaAI Audit Report</span>
                <span className="text-[11px] text-slate-500">{filename || 'Contract Analysis'}</span>
              </div>
              <span className="text-xs font-black px-3 py-1 rounded-full bg-rose-50 text-rose-700 border border-rose-200">
                Risk Score: {analysis.risk_score}/100
              </span>
            </div>

            <div>
              <span className="font-bold text-slate-900 text-xs block mb-1">Summary</span>
              <p className="text-slate-600 leading-relaxed text-xs">{analysis.summary}</p>
            </div>

            <div>
              <span className="font-bold text-slate-900 text-xs block mb-1.5">
                Identified Legal Risks ({analysis.risk_breakdown?.length || 0})
              </span>
              <ul className="space-y-1.5 list-disc pl-4 text-slate-600">
                {analysis.risk_breakdown?.slice(0, 4).map((r: any, idx: number) => (
                  <li key={idx}>
                    <strong className="text-slate-900">{r.issue}</strong> ({r.severity}) - {r.impact}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        {/* Modal Footer Actions */}
        <div className="px-6 py-4 bg-white flex items-center justify-end gap-3">
          <button
            onClick={handleCopyText}
            className="px-4 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs rounded-xl border border-slate-200 transition-colors flex items-center gap-1.5"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied to Clipboard' : 'Copy Full Text'}
          </button>
          <button
            onClick={handlePrint}
            className="px-5 py-2.5 bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs rounded-xl shadow-sm transition-all flex items-center gap-1.5 active:scale-95"
          >
            <Printer className="w-4 h-4" /> Print / Save as PDF
          </button>
        </div>
      </div>
    </div>
  );
};
